ALTER TABLE sessions ADD COLUMN affinity INTEGER DEFAULT 50;
ALTER TABLE sessions ADD COLUMN trust INTEGER DEFAULT 30;
ALTER TABLE sessions ADD COLUMN mood TEXT DEFAULT '平静';
ALTER TABLE sessions ADD COLUMN guard INTEGER DEFAULT 70;
