services:
  charsim:
    environment:
      - DATABASE_URL=postgresql://charsim:REDACTED@postgres:5432/charsim
    networks:
      - prod

networks:
  prod:
    external: true
    name: character-distill_prod
